# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - scheme: http        
      static_configs:
        - targets: ['52.183.69.248:9093']
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
    - "alertrules.yml"      
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['prometheus:9090']

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      # - targets: ['52.183.69.248:8080']
      - targets: ['cadvisor:8080']
              #- cadvisor:8080        

  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'grafana'
    scrape_interval: 5s
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'mongodb-exporter'
    scrape_interval: 5s
    static_configs:
            - targets: ['52.183.69.248:9216']

  - job_name: 'redis-exporter'
    scrape_interval: 5s
    static_configs:
            - targets: ['redis-exporter:9121']

  - job_name: 'rabbitmq-server'
    static_configs:
      - targets:
          - '52.183.69.248:15693'
          - '52.183.69.248:15694'
          - '52.183.69.248:15695'
          - 'rmq1:15692'
          - 'rmq2:15692'
          - 'rmq0-dist-tls:15692'
          - 'rmq1-dist-tls:15692'
          - 'rmq2-dist-tls:15692'
          - 'rmq0-qq:15692'
          - 'rmq1-qq:15692'
          - 'rmq2-qq:15692'
  - job_name: 'rabbitmq-perf-test'
    static_configs:
      - targets:
          # docker-compose-overview.yml
          - 'basic-get:8080'
          - 'basic-get-auto:8080'
          - 'greedy-consumer:8080'
          - 'publisher-confirms:8080'
          - 'slow-consumer-persistent:8080'
          - 'nack:8080'
          - 'unroutable-return:8080'
          - 'unroutable-drop:8080'
          # docker-compose-dist-tls.yml
          - 'stress-dist-tls:8080'
          # docker-compose-qq.yml
          - 'qq-moderate-load:8080'
  - job_name: 'rabbitmq-exporter'
    scrape_interval: 60s
    scrape_timeout: 59s
    static_configs:
      - targets:
          # docker-compose-dist-tls.yml
          - 'rabbitmq-exporter:9090'
